// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI622jmsW8YMZKVR8gxIr0HeutyO22xd0',
    appId: '1:624901911891:web:f12a99035afc7a8086dda6',
    messagingSenderId: '624901911891',
    projectId: 'portal-seae',
    authDomain: 'portal-seae.firebaseapp.com',
    storageBucket: 'portal-seae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLR3ktBc9SMCgdm3UMVRvGvkRPJwF17mM',
    appId: '1:624901911891:android:7ee822400957a6b486dda6',
    messagingSenderId: '624901911891',
    projectId: 'portal-seae',
    storageBucket: 'portal-seae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASEdZtTQopGEw-AtGZd9631EeIy6g0YvM',
    appId: '1:624901911891:ios:0cbc97064569430586dda6',
    messagingSenderId: '624901911891',
    projectId: 'portal-seae',
    storageBucket: 'portal-seae.firebasestorage.app',
    androidClientId: '624901911891-gtnob7u5icssrcgs6s7u2morn1ig3t8t.apps.googleusercontent.com',
    iosClientId: '624901911891-9mp0fiogrohejl6b7j42pr3mcurfsmtc.apps.googleusercontent.com',
    iosBundleId: 'br.org.seae.projetos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASEdZtTQopGEw-AtGZd9631EeIy6g0YvM',
    appId: '1:624901911891:ios:0cbc97064569430586dda6',
    messagingSenderId: '624901911891',
    projectId: 'portal-seae',
    storageBucket: 'portal-seae.firebasestorage.app',
    androidClientId: '624901911891-gtnob7u5icssrcgs6s7u2morn1ig3t8t.apps.googleusercontent.com',
    iosClientId: '624901911891-9mp0fiogrohejl6b7j42pr3mcurfsmtc.apps.googleusercontent.com',
    iosBundleId: 'br.org.seae.projetos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI622jmsW8YMZKVR8gxIr0HeutyO22xd0',
    appId: '1:624901911891:web:7f2e327ae2a60e3586dda6',
    messagingSenderId: '624901911891',
    projectId: 'portal-seae',
    authDomain: 'portal-seae.firebaseapp.com',
    storageBucket: 'portal-seae.firebasestorage.app',
  );

}